#! python


def build(ctx):

        
    ctx(
        features='run_py_script',
        source='plot_variables.py',
            deps=[
                ctx.path_to(ctx, "OUT_DATA", "productivity_clean.csv"),
                ctx.path_to(ctx, "IN_MODEL_CODE", "panel_model.py")
            ],
            target=ctx.path_to(ctx, "OUT_FIGURES", "independent_dependent_variables.png")
        )

    # from src.final.project_dependency_graph import make_project_dependency_graph

    # ctx.add_post_fun(make_project_dependency_graph)
