#! python


def build(ctx):        
        
    ctx(
        features='run_py_script',
        source='test_panel_model.py',
        deps=[
            ctx.path_to(ctx, "OUT_DATA", "productivity_clean.csv"),
            ctx.path_to(ctx, "IN_MODEL_CODE", "panel_model.py")        
        ],
        name='test_panel_model'
    )     
    
    ctx(
        features = 'run_py_script',
        source='hausman.py',
        deps=[
                ctx.path_to(ctx, "OUT_DATA", "productivity_clean.csv"),
                ctx.path_to(ctx, "IN_MODEL_CODE","panel_model.py")
        ],
        name='hausman'
    )
